name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    # Add steps to build/test your project here

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: ../../resources/ # specify files to include in the release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
