name: Create Release

permissions:
  contents: write

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add steps to build/test your project here

      - name: Run bundle script
        run: ./scripts/bundle_all.sh

      - name: Read Changelog
        id: changelog
        run: |
          echo "::set-output name=body::$(cat CHANGELOG.md)"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/ChiliKeys.app
          body: ${{ steps.changelog.outputs.body }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
