name: Create Release
permissions:
  contents: write
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Package
        run: pkgbuild --root src --identifier com.chilikeys.ChiliKeys --version ${{ github.ref_name }} --install-location ~ ChiliKeys-${{ github.ref_name }}.pkg
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ChiliKeys-${{ github.ref_name }}.pkg
